//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSuper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesVenta
    {
        public int idDetalleVenta { get; set; }
        public int idVenta { get; set; }
        public int idInventario { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Inventario Inventario { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
