//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSuper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int idEmpleado { get; set; }
        public string nombreEmpleado { get; set; }
        public string apellidos { get; set; }
        public int idCargo { get; set; }
        public int idSucursal { get; set; }
        public string dui { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
        public string codigoEmpleado { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Sucursale Sucursale { get; set; }
    }
}
